# Generated by Django 4.2.16 on 2024-09-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
